export * from './lambdas.extends'
export { default as buildURL } from './utils.buildURL'
export { default as compose } from './lambdas.compose'
export { default as flow } from './lambdas.flow'
export { default as formPairs } from './lambdas.formPairs'
export { default as head } from './lambdas.head'
export { default as pairs } from './lambdas.pairs'
export { default as reverse } from './lambdas.reverse'
export { default as tail } from './lambdas.tail'
export { default as cookieRead } from './utils.cookie.read'
export { default as isURLSomeOrigin } from './utils.isURLSomeOrigin'